"""Fix relationships

Revision ID: 5b641536615b
Revises: f89dbbfd0b50
Create Date: 2024-11-19 11:25:28.864580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b641536615b'
down_revision = 'f89dbbfd0b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('instructions', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('instructions')
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
